version: '3.7'

services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=db  
      - BARMAN_HOST=${BARMAN_HOST}
      - BARMAN_PASSWORD=${BARMAN_PASSWORD}
      - BARMAN_CONFIG_NAME=${BARMAN_PASSWORD}
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "archive_mode=on"
      - "-c"
      - "wal_level=replica"
      - "-c"
      - "archive_command='barman-wal-archive -U postgres $BARMAN_HOST $BARMAN_CONFIG_NAME /var/lib/postgresql/data/%p'"
    ports:
      - "5432:5432"
    volumes:
      - .db/:/var/lib/postgresql/data
    networks:
      - local
    labels:
      - "docky.main.service=True"
      - "docky.user=postgres"

networks:
  local:
